### ISSUE TITLE
Broken makefile?

### ISSUE THREAD

**Issue by cunidev** [Kostyan-nsk/hwp6s-kernel#1]
Thank you for your work. I am trying to use your kernel to build Postmarket OS on the P7-L10 but a makefile looks to be broken:

/hwp6s-kernel/blob/cm-13.0/arch/arm/mach-hi6620/pwrctrl/Makefile

Are lines #1 and #9 supposed to be that way? Thank you.

**Comment by Kostyan-nsk** [comment]
> Are lines #1 and #9 supposed to be that way? Thank you.

Such It was provided originally from Huawei. It doesn't break compilation to me.

**Comment by cunidev** [comment]
Thanks for replying! Hmm, it gives me a nasty "missing separator" error while building, also confirmed by this tool: https://tohtml.com/makefile/

**Comment by cunidev** [comment]
Someone else apparently had the same problem: https://stackoverflow.com/questions/42960134/what-is-wrong-with-makefile

**Comment by Kostyan-nsk** [comment]
What 'make' version are you running? Downgrade to version 3.81 or just remove line #9.

**Comment by cunidev** [comment]
Thanks, I solved that by removing such line
